Engine:
  Local:
    Bundles:
      - file://../agnostic-clickhouse-udf/tmp/bundle.tar.gz
      - file://../icepq/tmp/bundle.tar.gz#disable-cache=true
    Settings:
      allow_experimental_dynamic_type: 1
      enable_named_columns_in_function_tuple: 1
      send_logs_level: warning
      enable_json_type: 1
      enable_dynamic_type: 1
      schema_inference_make_columns_nullable: auto
      remote_filesystem_read_prefetch: 0
      input_format_parquet_use_native_reader: 0
      output_format_parquet_string_as_string: 0
      output_format_parquet_use_custom_encoder: 1
      output_format_parquet_write_page_index: 1
      output_format_parquet_write_bloom_filter: 1
      output_format_parquet_parallel_encoding: 0
      max_execution_time: 3600
      max_bytes_ratio_before_external_group_by: 0.01
      max_bytes_before_external_group_by: 134217728
      max_bytes_ratio_before_external_sort: 0.01
      max_bytes_before_external_sort: 134217728
      s3_max_connections: 50

Init:
  Queries:
    - init.sql
  StopAfter: 1

Source:
  Query: source.sql
  StopOnEmpty: true

Processors:
  - Debug:
      Pretty: true
  - Map:
      Queries:
        - merge_files.sql
      ClickhouseSettings:
        max_threads: 1
        s3_max_inflight_parts_for_one_file: 1
        s3_max_upload_part_size: 67108864

        # s3_allow_parallel_part_upload=0,
        # s3_max_inflight_parts_for_one_file=1,
        # s3_max_upload_part_size=67108864,
        # max_block_size=32768,
        # min_insert_block_size_rows=0,
        # min_insert_block_size_bytes=33554432
  - Batch:
      Queries:
        - merge_merges.sql
  - Debug:
      Pretty: true 
  - Map: 
      Queries:
        - merge_table.sql