Engine:
  Local:
    Bundles:
      - https://github.com/agnosticeng/clickhouse-evm/releases/download/v0.0.17/clickhouse-evm_0.0.17_{{ .PLATFORM | default "linux_amd64_v3" }}.tar.gz
    Settings:
      send_logs_level: warning
      allow_experimental_dynamic_type: 1
      allow_experimental_json_type: 1
      enable_dynamic_type: 1
      enable_json_type: 1
      enable_named_columns_in_function_tuple: 1
      schema_inference_make_columns_nullable: auto
      remote_filesystem_read_prefetch: 0
      glob_expansion_max_elements: 1000
      input_format_parquet_use_native_reader: 1
      output_format_parquet_string_as_string: 0
      output_format_parquet_use_custom_encoder: 1
      output_format_parquet_write_page_index: 1
      output_format_parquet_write_bloom_filter: 1
      max_threads: 100
      max_download_threads: 100

Source:
  Query: source
  StopAfter: 1

Processors:
  - Debug: {}
  - Apply: 
      Queries:
        - fetch_abis
        - generate_decoding_dataset
        - check_decoding_dataset
        - save_as_daily_parquet
        - save_as_latest_parquet